# Generated by Django 3.2.16 on 2023-04-19 20:14

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('dishes', '0001_initial'), ('dishes', '0002_initial'), ('dishes', '0003_alter_dish_recipe'), ('dishes', '0004_auto_20230417_2153'), ('dishes', '0005_alter_ingredient_name_normalized'), ('dishes', '0006_alter_ingredient_name_normalized'), ('dishes', '0007_auto_20230418_1535'), ('dishes', '0008_auto_20230419_2250')]

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название. Максимум 100 символов', max_length=100, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип блюда',
                'verbose_name_plural': 'типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название. Максимум 100 символов', max_length=100, unique=True, verbose_name='название')),
                ('moderation_status', models.CharField(choices=[('not verified', 'Не проверено'), ('verified', 'Проверено')], default='not verified', max_length=12, verbose_name='статус модерации')),
                ('name_normalized', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название блюда. Максимум 100 символов', max_length=100, verbose_name='название')),
                ('image_main', models.ImageField(help_text='Добавьте красивую фотографию блюда', upload_to='dish/main/%Y/%m/%d', verbose_name='главное фото')),
                ('recipe', tinymce.models.HTMLField(help_text='Рецепт по приготовлению', validators=[django.core.validators.MinLengthValidator(50, 'Рецепт слишком маленький. Пожалуйста, распишите этапы приготовления более подробно.')], verbose_name='рецепт')),
                ('complexity', core.models.IntegerRangeField(default=5, help_text='Сложность блюда от 1 до 5', verbose_name='сложность блюда')),
                ('cooking_time', models.DurationField(help_text='Время готовки', verbose_name='время готовки')),
                ('moderation_status', models.CharField(choices=[('sent', 'Отправлено модератору'), ('handling', 'В обработке'), ('added', 'Добавлено'), ('rejected', 'Отклонено')], default='sent', max_length=8, verbose_name='статус модерации')),
                ('is_on_home_page', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы отобразить на главной странице', verbose_name='отображать на главной странице')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор блюда')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='добавьте теги(используйте клавишу enter для ввода)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='теги')),
                ('type', models.ForeignKey(help_text='Укажите тип блюда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.dishtype', verbose_name='тип блюда')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IngredientInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=None, help_text='Укажите объём ингредиента', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='объём ингредиента')),
                ('quantity_type', models.CharField(choices=[('kg', 'килограмм'), ('gram', 'грамм'), ('liters', 'литр'), ('milliliters', 'миллилитр'), ('table spoon', 'столовая ложка'), ('tea spoon', 'чайная ложка'), ('piece', 'штука'), ('pinch', 'щепотка')], help_text='Укажите тип объёма ингредиента. Максимум 100 символов', max_length=11, verbose_name='тип объёма')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dishes.dish')),
                ('ingredient', models.ForeignKey(help_text='Укажите название ингредиента. Максимум 100 символов', on_delete=django.db.models.deletion.CASCADE, to='dishes.ingredient', verbose_name='название ингредиента')),
            ],
            options={
                'verbose_name': 'объект ингредиента',
                'verbose_name_plural': 'объекты ингредиентов',
            },
        ),
    ]
