# Generated by Django 3.2.16 on 2023-04-05 20:37

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    replaces = [
        ('dishes', '0001_initial'),
        ('dishes', '0002_auto_20230405_2256'),
        ('dishes', '0003_auto_20230405_2313'),
        ('dishes', '0004_auto_20230405_2319'),
        ('dishes', '0005_auto_20230405_2322'),
        ('dishes', '0006_auto_20230405_2331'),
    ]

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название. Максимум 100 символов',
                        max_length=100,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название. Максимум 100 символов',
                        max_length=100,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'граммовка',
                'verbose_name_plural': 'граммовки',
            },
        ),
        migrations.CreateModel(
            name='IngredientsInstance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        help_text='Укажите количество',
                        verbose_name='количество ингредиента',
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        help_text='Укажите название ингредиента. Максимум 100 символов',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='dishes.ingredient',
                        verbose_name='название ингредиента',
                    ),
                ),
                (
                    'quantity_type',
                    models.ForeignKey(
                        help_text='Укажите тип граммовки ингредиента. Максимум 100 символов',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dishes.quantitytype',
                        verbose_name='тип граммовки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'объект ингредиента',
                'verbose_name_plural': 'объекты ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название. Максимум 100 символов',
                        max_length=100,
                        verbose_name='название',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тип блюда',
                'verbose_name_plural': 'типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Укажите название блюда. Максимум 100 символов',
                        max_length=100,
                        verbose_name='название',
                    ),
                ),
                (
                    'type',
                    models.ForeignKey(
                        help_text='Укажите тип блюда',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dishes.dishtype',
                        verbose_name='тип блюда',
                    ),
                ),
                (
                    'recipe',
                    models.TextField(
                        help_text='Рецепт по приготовлению',
                        verbose_name='рецепт',
                    ),
                ),
                (
                    'complexity',
                    core.models.IntegerRangeField(
                        default=10,
                        help_text='Сложность блюда от 1 до 10',
                        verbose_name='сложность блюда',
                    ),
                ),
                (
                    'cooking_time',
                    models.PositiveSmallIntegerField(
                        help_text='Время готовки в часах',
                        verbose_name='время готовки',
                    ),
                ),
                (
                    'ingredients',
                    models.ManyToManyField(
                        help_text='Перечислите необходимые ингредиенты',
                        to='dishes.IngredientsInstance',
                        verbose_name='ингредиенты',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='users.user',
                        verbose_name='автор блюда',
                    ),
                ),
                (
                    'date_created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата создания'
                    ),
                ),
                (
                    'date_updated',
                    models.DateTimeField(
                        auto_now=True, verbose_name='дата последнего изменения'
                    ),
                ),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
    ]
