# Generated by Django 3.2.16 on 2023-04-17 17:54

import django.core.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=tinymce.models.HTMLField(help_text='Рецепт по приготовлению', validators=[django.core.validators.MinLengthValidator(50, 'Рецепт слишком маленький. Пожалуйста, распишите этапы приготовления более подробно.')], verbose_name='рецепт'),
        ),
    ]
