# Generated by Django 3.2.16 on 2023-04-07 13:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'dishes',
            '0002_alter_dish_cooking_time_squashed_0004_alter_dish_cooking_time',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_on_home_page',
            field=models.BooleanField(
                default=False,
                help_text='Поставьте галочку, чтобы отобразить на главной странице',
                verbose_name='отображать на главной странице',
            ),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooking_time',
            field=models.DurationField(
                default=datetime.timedelta(seconds=1800),
                help_text='Время готовки',
                verbose_name='время готовки',
            ),
        ),
    ]
