# Generated by Django 3.2.16 on 2023-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dishes', '0003_auto_20230407_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='processing_status',
            field=models.CharField(
                choices=[
                    ('sent', 'Отправлено модератору'),
                    ('handling', 'В обработке'),
                    ('added', 'Добавлено'),
                    ('rejected', 'Отклонено'),
                ],
                default='sent',
                max_length=8,
                verbose_name='статус обработки',
            ),
        ),
    ]
