# Generated by Django 3.2.16 on 2023-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dishes', '0003_alter_dish_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='moderation_status',
            field=models.CharField(
                choices=[
                    ('not verified', 'Не проверено'),
                    ('verified', 'Проверено'),
                ],
                default='not verified',
                max_length=12,
                verbose_name='статус модерации',
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_normalized',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
