# Generated by Django 3.2.16 on 2023-04-07 16:59

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
        ('dishes', '0004_dish_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInstance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        help_text='Укажите объём ингредиента',
                        verbose_name='объём ингредиента',
                    ),
                ),
                (
                    'quantity_type',
                    models.CharField(
                        choices=[
                            ('kg', 'килограмм'),
                            ('gram', 'грамм'),
                            ('liters', 'литр'),
                            ('milliliters', 'миллилитр'),
                            ('table spoon', 'столовая ложка'),
                            ('tea spoon', 'чайная ложка'),
                        ],
                        help_text='Укажите тип объёма ингредиента. Максимум 100 символов',
                        max_length=11,
                        verbose_name='тип объёма',
                    ),
                ),
            ],
            options={
                'verbose_name': 'объект ингредиента',
                'verbose_name_plural': 'объекты ингредиентов',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_on_home_page',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='processing_status',
        ),
        migrations.AlterField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='users.user',
                verbose_name='автор блюда',
            ),
        ),
        migrations.AlterField(
            model_name='dish',
            name='complexity',
            field=core.models.IntegerRangeField(
                default=5,
                help_text='Сложность блюда от 1 до 5',
                verbose_name='сложность блюда',
            ),
        ),
        migrations.DeleteModel(
            name='IngredientsInstance',
        ),
        migrations.DeleteModel(
            name='QuantityType',
        ),
        migrations.AddField(
            model_name='ingredientinstance',
            name='dish',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'
            ),
        ),
        migrations.AddField(
            model_name='ingredientinstance',
            name='ingredient',
            field=models.ForeignKey(
                help_text='Укажите название ингредиента. Максимум 100 символов',
                on_delete=django.db.models.deletion.CASCADE,
                to='dishes.ingredient',
                verbose_name='название ингредиента',
            ),
        ),
    ]
