# Generated by Django 3.2.16 on 2023-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20230417_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name_normalized',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
