# Generated by Django 3.2.16 on 2023-04-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
        ('dishes', '0005_auto_20230407_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='is_on_home_page',
            field=models.BooleanField(
                default=False,
                help_text='Поставьте галочку, чтобы отобразить на главной странице',
                verbose_name='отображать на главной странице',
            ),
        ),
        migrations.AddField(
            model_name='dish',
            name='moderation_status',
            field=models.CharField(
                choices=[
                    ('sent', 'Отправлено модератору'),
                    ('handling', 'В обработке'),
                    ('added', 'Добавлено'),
                    ('rejected', 'Отклонено'),
                ],
                default='sent',
                max_length=8,
                verbose_name='статус обработки',
            ),
        ),
        migrations.AlterField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.user',
                verbose_name='автор блюда',
            ),
        ),
        migrations.AlterField(
            model_name='ingredientinstance',
            name='dish',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredients',
                to='dishes.dish',
            ),
        ),
        migrations.AlterField(
            model_name='ingredientinstance',
            name='quantity',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Укажите объём ингредиента',
                verbose_name='объём ингредиента',
            ),
        ),
    ]
