# Generated by Django 3.2.16 on 2023-04-09 19:54

import django.core.validators
from django.db import migrations
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('dishes', '0008_alter_dish_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=tinymce.models.HTMLField(help_text='Рецепт по приготовлению', validators=[django.core.validators.MinLengthValidator(300, 'Рецепт слишком маленький. Пожалуйста, распишите этапы приготовления более подробно.')], verbose_name='рецепт'),
        ),
    ]
