# Generated by Django 3.2.16 on 2023-04-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dishes', '0009_auto_20230409_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishImageMain',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image_main',
                    models.ImageField(upload_to='dish/main/%Y/%m/%d'),
                ),
            ],
            options={
                'verbose_name': 'главное фото',
                'verbose_name_plural': 'главные фото',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='dishes.dishimagemain',
                verbose_name='главное фото',
            ),
        ),
    ]
