# Generated by Django 3.2.16 on 2023-04-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dishes', '0010_auto_20230409_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='dishes.dishimagemain',
                verbose_name='главное фото',
            ),
        ),
    ]
