# Generated by Django 3.2.16 on 2023-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.AddField(
            model_name='dish',
            name='image_main',
            field=models.ImageField(null=True, upload_to='dish/main/%Y/%m/%d', verbose_name='главное фото'),
        ),
        migrations.DeleteModel(
            name='DishImageMain',
        ),
    ]
