# Generated by Django 3.2.16 on 2023-04-10 08:02

import taggit_selectize.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('dishes', '0013_alter_dish_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_main',
            field=models.ImageField(
                help_text='Добавьте красивую фотографию блюда',
                upload_to='dish/main/%Y/%m/%d',
                verbose_name='главное фото',
            ),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
    ]
