# Generated by Django 3.2.16 on 2023-04-10 08:21

import taggit_selectize.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('dishes', '0014_auto_20230410_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(
                help_text='добавьте теги(используйте клавишу enter для ввода)',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='теги',
            ),
        ),
    ]
