[tool.black]
line-length = 79
include = '\.pyi?$'
skip-string-normalization = true
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | README.md
  | .gitignore
  | .env
)
'''

[tool.isort]
profile = 'black'
py_version = 310
skip_gitignore = true
line_length = 79
use_parentheses = true
known_first_party=['core', 'dishes', 'home', 'users', 'feedback' ]
force_alphabetical_sort_within_sections = true