# Generated by Django 3.2.16 on 2023-04-19 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('feedback', '0001_initial'), ('feedback', '0002_alter_feedback_text'), ('feedback', '0003_alter_feedback_mail'), ('feedback', '0004_auto_20230417_2054')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, verbose_name='электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст сообщения')),
                ('created_on', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата и время создания')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('handling', 'В обработке'), ('answered', 'Ответ дан')], default='received', max_length=8, verbose_name='статус')),
                ('personal_information', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='feedback.personalinformation')),
            ],
            options={
                'verbose_name': 'фидбек',
                'verbose_name_plural': 'фидбеки',
            },
        ),
    ]
