# Generated by Django 3.2.16 on 2023-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
