# Generated by Django 3.2.16 on 2023-04-17 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0003_alter_feedback_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        max_length=254, verbose_name='электронная почта'
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mail',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='дата и время создания',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'Получено'),
                    ('handling', 'В обработке'),
                    ('answered', 'Ответ дан'),
                ],
                default='received',
                max_length=8,
                verbose_name='статус',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='текст сообщения'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='personal_information',
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='personal_information',
                to='feedback.personalinformation',
            ),
        ),
    ]
